<?php
/*
Template Name: Template Privacy notice
Template Post Type: page
*/
?>
<?php get_header(); ?>
<?php $pricing_field = get_fields(); ?>
<section class="main">
    <div class="container">
        <h1 class="title"><span><?php the_title(); ?></span> <?php the_title(); ?></h1>
    </div>
</section>
<section class="content">
    <div class="wrapper">
        <p>In providing your dental care and treatment, we will ask for information about you and your health. Occasionally, we may receive information from other providers who have been involved in providing your care. This privacy notice describes the type of personal information we hold, why we hold it and what we do with it.</p>
        <h3>About us</h3>
        <p>We are Royston AesthetiX, operating at 6-8 Market Hill, Royston, SG8 9JL and various satellite practices within Antwerp Dental Group. Dr. Raj Wadhwani is responsible for keeping information that we hold about you secure. Those at the practice who have access to your information include dentists and other dental professionals involved with your care and treatment. This includes the reception staff responsible for the management and administration of the practice.</p>
        <p>Our data protection officer, Mrs. Rita Lacey ensures that the practice complies with data protection requirements to ensure that we collect, use, store and dispose of your information responsibly. You can contact our data protection officer, Rita, by email at:
           <br> <a class="mail" href="mailto:rita.lacey@antwerpdentalgroup.co.uk">rita.lacey@antwerpdentalgroup.co.uk</a> or by phone on <a class="tel" href="tel:01223513148">01223 513148</a>
        </p>
        <h3>Information that we hold</h3>
        <p>We can only keep and use information for specific reasons set out in the law. If we want to keep and use information about your health, we can only do so in particular circumstances. Below, we describe the information we hold and why, and the lawful basis for collecting and using it.</p>
        <h3>Contact details</h3>
        <p>We hold personal information about you including your name, date of birth, national insurance number, NHS number, address, telephone number and email address. This information allows us to fulfil our contract with you to provide appointments. We will also use the information to send you reminders and recall appointments as we have a legitimate interest to ensure your continuing care and to make you aware of our services and important health updates.</p>
        <h3>Dental records</h3>
        <p>We hold information about your dental and general health, including – Clinical records made by dentists and other dental professionals involved with your care and treatment :</p>
        <ul>
            <li>X-rays, clinical photographs, digital scans of your mouth and teeth, and study models</li>
            <li>Medical and dental histories – Treatment plans and consent – Notes of conversations with you about your care</li>
            <li>Dates of your appointments</li>
            <li>Details of any complaints you have made and how these complaints were dealt with</li>
            <li>Correspondence with you and other health professionals or institutions.</li>
        </ul>
        <p>We collect and use this information to allow us to fulfil our contract with you to discuss your treatment options and provide dental care that meets your needs. We also use this information for the legitimate interest of ensuring the quality of the treatment we provide.</p>
        <h3>Financial information</h3>
        <p>We hold information about the fees we have charged, the amounts you have paid and some payment details. This information forms part of our contractual obligation to you to provide dental care and allows us to meet legal financial requirements. Where your dental care is provided under the terms of the NHS, we are required to complete statutory forms to allow payments to be processed. This is an NHS requirement.</p>
        <h3>Your use of our website</h3>
        <p>Our website uses Google Analytics to help analyze how users use the site. The tool uses “cookies,” which are text files placed on your computer, to collect standard Internet log information and visitor behaviour information in an anonymous form. The information generated by the cookie about your use of the website (including IP address) is transmitted to Google. This information is then used to evaluate visitors’ use of the website and to compile statistical reports on website activity. This enables us to improve the user experience, and friendliness of our site to be able to more readily access important health information.</p>
        <p>We will never (and will not allow any third party to) use the statistical analytics tool to track or to collect any Personally Identifiable Information (PII) of visitors to our site. Google will not associate your IP address with any other data held by Google. Neither we nor Google will link, or seek to link, an IP address with the identity of a computer user. We will not associate any data gathered from this site with any Personally Identifiable Information from any source, unless you explicitly submit that information via a fill-in form on our website.</p>
        <h3>How we use your information</h3>
        <p>To provide you with the dental care and treatment that you need, we require up-to-date and accurate information about you. We will only share your information where necessary with :</p>
        <ul>
            <li>Health Education England</li>
            <li>Denplan from Simply Health Professionals</li>
            <li>Chrysalis Dental Finance (with your consent), when you are seeking funding for dental treatment</li>
            <li>Insurance firms in connection with dental insurance claims</li>
            <li>Lawyers (with your consent), in connection with a claim you are pursuing</li>
            <li>An enduring power of attorney</li>
        </ul>
        <p>We may contact you to conduct patient surveys or to find out if you are happy with the treatment you received for quality control purposes. We will seek your preference for how we contact you about your dental care. Our usual methods are telephone, email or letter.</p>
        <p>If we wish to use your information for dental research or dental education, we will discuss this with you and seek your consent. Depending on the purpose and if possible, we will anonymise your information. If this is not possible we will inform you and discuss your options. We may use your contact details to inform you of products and services available at our Practice.</p>
        <h3>Sharing information</h3>
        <p>Your information is normally used only by those working at the practice but there may be instances where we need to share it – for example, with:</p>
        <ul>
            <li>Your doctor</li>
            <li>The hospital or community dental services or other health professionals caring for you</li>
            <li>Specialist dental or medical services to which we may refer you</li>
            <li>NHS payment authorities</li>
            <li>The Department for Work and Pensions and its agencies, where you are claiming exemption or remission from NHS charges</li>
            <li>Dental laboratories</li>
            <li> Debt collection agencies</li>
            <li>Private dental schemes of which you are a member.</li>
        </ul>
        <p>We will only disclose your information on a need-to-know basis and will limit any information that we share to the minimum necessary. We will let you know in advance if we send your medical information to another medical provider and we will give you the details of that provider at that time. In certain circumstances or if required by law, we may need to disclose your information to a third party not connected with your health care, including HMRC or other law enforcement or government agencies.</p>
        <h3>Keeping your information safe</h3>
        <p>We store your personal information securely on our practice computer system and in a manual filing system. Your information cannot be accessed by those who do not work at the practice; only those working at the practice have access to your information. They understand their legal responsibility to maintain confidentiality and follow practice procedures to ensure this. We take precautions to ensure security of the practice premises, the practice filing systems and computers. We use high-quality specialist dental software to record and use your personal information safely and effectively. Our computer system has a secure audit trail and we back-up information routinely. We use cloud computing facilities for storing some of your information. The practice has a rigorous agreement with our provider to ensure that we meet the obligations described in this policy and that we keep your information securely. We keep your records for 10 years after the date of your last visit to the Practice or until you reach the age of 25 years, whichever is the longer. At your request, we will delete non-essential information (for example some contact details) before the end of this period.</p>
        <h3>Access to your information and other rights</h3>
        <p>You have a right to access the information that we hold about you and to receive a copy. We do not usually charge you for copies of your information; if we pass on a charge, we will explain the reasons. You can also request us to</p>
        <ul>
            <li>Correct any information that you believe is inaccurate or incomplete. If we have disclosed that information to a third party, we will let them know about the change.</li>
            <li>Erase some of the information we hold. For legal reasons, we may be unable to erase certain information (for example, information about your dental treatment). However, we can, if you ask us to, delete some contact details and other non-clinical information.</li>
            <li>Stop using your information – for example, sending you reminders for appointments or information about our service. Even if you have given us consent to send you marketing information, you may withdraw that consent at any time.</li>
            <li>Stop using information if you believe the information is inaccurate or you believe we are using your information illegally.</li>
            <li>Supply your information electronically to another dentist. If we are relying on your consent to use your personal information for a particular purpose, you may withdraw your consent at any time and we will stop using your information for that purpose. All requests should be made by email to our data protection officer at : <a class="mail" href="mailto:rita.lacey@antwerpdentalgroup.co.uk">rita.lacey@antwerpdentalgroup.co.uk</a></li>
        </ul>
        <h3>If you do not agree</h3>
        <p>If you do not wish us to use your personal information as described, you should discuss the matter with your dentist. If you object to the way that we collect and use your information, we may not be able to continue to provide your dental care. If you have any concerns about how we use your information and you do not feel able to discuss it with your dentist or anyone at the practice, you should contact The Information Commissioner’s Office (ICO), Wycliffe House, Water Lane, Wilmslow, Cheshire SK9 5AF (0303 123 1113 or 01625 545745).</p>
        <div class="date"><span>Date:</span> 25th May 2018</div>
        <div class="date"><span>Review date:</span> 24th May 2019</div>
    </div>
</section>
<?php get_template_part( 'template-part/form-page' );  ?>
<?php get_template_part( 'template-part/find-us' );  ?>
<?php get_footer(); ?>
